Coloborador/Coloborador/Models/ColaboradorModel.cs
using System.ComponentModel.DataAnnotations;

namespace Coloborador.Models
{
    public class ColaboradorModel
    {
        public int id { get; set; }

        [Required(ErrorMessage = "El campo nombres es obligatorio")]
        public string? nombres { get; set; }

        [Required(ErrorMessage = "El campo apellidos es obligatorio")]
        public string? apellidos { get; set; }

        [Required(ErrorMessage = "El campo fecha nacimiento es obligatorio")]
        public string? fecha_nacimiento { get; set; }
        [Required(ErrorMessage = "El campo estado civil es obligatorio")]
        public string? estado_civil { get; set; }

        [Required(ErrorMessage = "El campo grado academico es obligatorio")]
        public string? grado_academico { get; set; }

        [Required(ErrorMessage = "El campo direccion es obligatorio")]
        public string? direccion { get; set; }

    }
}

Coloborador/Coloborador/Models/ErrorViewModel.cs
namespace Coloborador.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Coloborador/Coloborador/Controllers/HomeController.cs
using Coloborador.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Coloborador.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Coloborador/Coloborador/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using Coloborador.Datos;
using Coloborador.Models;

namespace Coloborador.Controllers
{
    public class MantenedorController : Controller
    {
        ColaboradorDatos _colaboradorDatos = new ColaboradorDatos();

        public IActionResult Listar()
        {
            //MONTRARA UNA LISTA DE CONTACTOS
            var oLista = _colaboradorDatos.Listar();
            return View(oLista);
        }
        public IActionResult Guardar()
        {
            //METODO SOLO DEVUELVE LA VISTA
            return View();
        }
        [HttpPost]
        public IActionResult Guardar(ColaboradorModel oColaborador)
        {
            //METODO RECIBE EL OBJETO PARA GUARDARLO A LA BD
            if (!ModelState.IsValid)
                return View();


            var respuesta = _colaboradorDatos.Guardar(oColaborador);
            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
                return View();
        }


        public IActionResult Editar(int id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var ocolaborador = _colaboradorDatos.Obtener(id);
            return View(ocolaborador);
        }
        [HttpPost]
        public IActionResult Editar(ColaboradorModel oColaborador)
        {
            //METODO RECIBE EL OBJETO PARA EDITARLO A LA BD
            if (!ModelState.IsValid)
                return View();


            var respuesta = _colaboradorDatos.Editar(oColaborador);
            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
                return View();
        }
        public IActionResult Eliminar(int id)
        {
            //METODO SOLO DEVUELVE LA VISTA
            var ocolaborador = _colaboradorDatos.Obtener(id);
            return View(ocolaborador);
        }
        [HttpPost]
        public IActionResult Eliminar(ColaboradorModel oColaborador)
        {
            //METODO RECIBE EL OBJETO PARA ELIMINARLO DE LA BD



            var respuesta = _colaboradorDatos.Eliminar(oColaborador.id);
            if (respuesta)
            {
                return RedirectToAction("Listar");
            }
            else
                return View();
        }



    }
}

Coloborador/Coloborador/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Coloborador/Coloborador/Views/Mantenedor/Editar.cshtml
@model ColaboradorModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">

    <div class="card-header">
        Editar Colaborador
    </div>

    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for="id" type="text" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombres" type="text" class="form-control">
                <span asp-validation-for="nombres" class="text-danger"> </span>

            </div>
            <div class="mb-3">
                <label f class="form-label">Apellidos</label>
                <input asp-for="apellidos" type="text" class="form-control">
                <span asp-validation-for="apellidos" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Fecha Nacimiento</label>
                <input asp-for="fecha_nacimiento" type="date" class="form-control">
                <span asp-validation-for="fecha_nacimiento" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Estado Civil</label>
                <input asp-for="estado_civil" type="text" class="form-control">
                <span asp-validation-for="estado_civil" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Grado Academico</label>
                <input asp-for="grado_academico" type="text" class="form-control">
                <span asp-validation-for="grado_academico" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Direccion</label>
                <input asp-for="direccion" type="text" class="form-control">
                <span asp-validation-for="direccion" class="text-danger"> </span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>



    </div>
</div>

Coloborador/Coloborador/Views/Mantenedor/Eliminar.cshtml
@model ColaboradorModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card">

    <div class="card-header">
        Elimnar Colaborador
    </div>

    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="id" type="hidden" class="form-control">
            <div class="alert alert-danger" role="alert">
                Desea Eliminar el Contacto? : @Html.DisplayTextFor(m => m.nombres) ?
            </div>


            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>



    </div>
</div>

Coloborador/Coloborador/Views/Mantenedor/Guardar.cshtml
@model ColaboradorModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">

    <div class="card-header">
        Crear Colaborador
        </div>

    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label class="form-label">Nombres</label>
                <input asp-for="nombres" type="text" class="form-control">
                <span asp-validation-for="nombres" class="text-danger"> </span>

            </div>
            <div class="mb-3">
                <label f class="form-label">Apellidos</label>
                <input asp-for="apellidos" type="text" class="form-control">
                <span asp-validation-for="apellidos" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Fecha Nacimiento</label>
                <input asp-for="fecha_nacimiento" type="date" class="form-control">
                <span asp-validation-for="fecha_nacimiento" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Estado Civil</label>
                <input asp-for="estado_civil" type="text" class="form-control">
                <span asp-validation-for="estado_civil" class="text-danger"> </span>
            </div>
             <div class="mb-3">
                <label f class="form-label">Grado Academico</label>
                <input asp-for="grado_academico" type="text" class="form-control">
                <span asp-validation-for="grado_academico" class="text-danger"> </span>
            </div>
            <div class="mb-3">
                <label f class="form-label">Direccion</label>
                <input asp-for="direccion" type="text" class="form-control">
                <span asp-validation-for="direccion" class="text-danger"> </span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>



    </div>
</div>

Coloborador/Coloborador/Views/Mantenedor/Listar.cshtml
@model List<ColaboradorModel>

@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">

    <div class="card-header">
        Lista Colaboradores
    </div>

    <div class="card-body">

        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Fecha Nacimiento</th>
                    <th>Estado Civil</th>
                    <th>Grado Academico</th>
                    <th>Direccion</th>
                    <th></th>
                </tr>

            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.nombres</td>
                        <td>@item.apellidos</td>
                        <td>@item.fecha_nacimiento</td>
                        <td>@item.estado_civil</td>
                        <td>@item.grado_academico</td>
                        <td>@item.direccion</td>
                        <th>
                            <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-id="@item.id">Editar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-id="@item.id">Eliminar</a>
                        </th>

                    </tr>

                }

            </tbody>




        </table>

    </div>
</div>

Coloborador/Coloborador/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Coloborador</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Coloborador.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Coloborador</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Coloborador - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>